kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: print-name-route
  labels:
    app: print-name
spec:
  to:
    kind: Service
    name: print-name-svc
  port:
    targetPort: 9000
  wildcardPolicy: None
