apiVersion: v1
kind: Service
metadata:
  name: print-name-svc
  labels:
    app: print-name
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: print-name

